title: Just the Docs Practice
description: Learning how to use the template
theme: just-the-docs

url: https://rtreddick.github.io/just-the-docs-practice

aux_links:
  Template Repository: https://github.com/rtreddick/just-the-docs-practice
